language: java
jdk:
  - openjdk8

# Pre-testing installs
install:
  - echo "nothing to install.."

# Scripts to be run such as tests
before_script:
  - echo "before script is nothiiiiing...."

script:
  - ./mvnw clean install -Drevision=$(git rev-parse --short HEAD)

#docker push to docker hub
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag docker-maven-plugin $DOCKER_USERNAME/docker-maven-plugin
  - docker push $DOCKER_USERNAME/docker-maven-plugin